[package]
name = "bean-importer"
version = "0.1.0"
authors = ["hui <ihulufei@icloud.com>"]
edition = "2018"

[dependencies]
csv="1.1"
structopt = "0.3.12"
anyhow = "1.0.28"
thiserror = "1.0.14"
fehler = "1.0.0"
toml_edit = "0.1.5"
